application: gogaecms
version: 1
runtime: go
api_version: go1
module: default

handlers:
- url: /admin/(datas|templates|settings)?$
  static_files: admin/index.html
  upload: admin/index.html

- url: /admin
  static_dir: admin

- url: /.*
  script: _go_app
